package com.practica.dao.general.model;

public class Persona {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.cedula
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private Integer cedula;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.nombre
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.apellido_1
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String apellido_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.apellido_2
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String apellido_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.telefono_1
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private Integer telefono_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.telefono_2
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private Integer telefono_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.correo
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String correo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.direccion
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String direccion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.codigo_prog_academico
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String codigo_prog_academico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persona.codigo_cargo
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String codigo_cargo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.cedula
     *
     * @return the value of persona.cedula
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public Integer getCedula() {
        return cedula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.cedula
     *
     * @param cedula the value for persona.cedula
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setCedula(Integer cedula) {
        this.cedula = cedula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.nombre
     *
     * @return the value of persona.nombre
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.nombre
     *
     * @param nombre the value for persona.nombre
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.apellido_1
     *
     * @return the value of persona.apellido_1
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getApellido_1() {
        return apellido_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.apellido_1
     *
     * @param apellido_1 the value for persona.apellido_1
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setApellido_1(String apellido_1) {
        this.apellido_1 = apellido_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.apellido_2
     *
     * @return the value of persona.apellido_2
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getApellido_2() {
        return apellido_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.apellido_2
     *
     * @param apellido_2 the value for persona.apellido_2
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setApellido_2(String apellido_2) {
        this.apellido_2 = apellido_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.telefono_1
     *
     * @return the value of persona.telefono_1
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public Integer getTelefono_1() {
        return telefono_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.telefono_1
     *
     * @param telefono_1 the value for persona.telefono_1
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setTelefono_1(Integer telefono_1) {
        this.telefono_1 = telefono_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.telefono_2
     *
     * @return the value of persona.telefono_2
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public Integer getTelefono_2() {
        return telefono_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.telefono_2
     *
     * @param telefono_2 the value for persona.telefono_2
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setTelefono_2(Integer telefono_2) {
        this.telefono_2 = telefono_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.correo
     *
     * @return the value of persona.correo
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.correo
     *
     * @param correo the value for persona.correo
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.direccion
     *
     * @return the value of persona.direccion
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.direccion
     *
     * @param direccion the value for persona.direccion
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.codigo_prog_academico
     *
     * @return the value of persona.codigo_prog_academico
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getCodigo_prog_academico() {
        return codigo_prog_academico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.codigo_prog_academico
     *
     * @param codigo_prog_academico the value for persona.codigo_prog_academico
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setCodigo_prog_academico(String codigo_prog_academico) {
        this.codigo_prog_academico = codigo_prog_academico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persona.codigo_cargo
     *
     * @return the value of persona.codigo_cargo
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getCodigo_cargo() {
        return codigo_cargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persona.codigo_cargo
     *
     * @param codigo_cargo the value for persona.codigo_cargo
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setCodigo_cargo(String codigo_cargo) {
        this.codigo_cargo = codigo_cargo;
    }
}