package com.practica.dao.general.model;

import java.util.ArrayList;
import java.util.List;

public class PersonaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public PersonaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCedulaIsNull() {
            addCriterion("cedula is null");
            return (Criteria) this;
        }

        public Criteria andCedulaIsNotNull() {
            addCriterion("cedula is not null");
            return (Criteria) this;
        }

        public Criteria andCedulaEqualTo(Integer value) {
            addCriterion("cedula =", value, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaNotEqualTo(Integer value) {
            addCriterion("cedula <>", value, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaGreaterThan(Integer value) {
            addCriterion("cedula >", value, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaGreaterThanOrEqualTo(Integer value) {
            addCriterion("cedula >=", value, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaLessThan(Integer value) {
            addCriterion("cedula <", value, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaLessThanOrEqualTo(Integer value) {
            addCriterion("cedula <=", value, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaIn(List<Integer> values) {
            addCriterion("cedula in", values, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaNotIn(List<Integer> values) {
            addCriterion("cedula not in", values, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaBetween(Integer value1, Integer value2) {
            addCriterion("cedula between", value1, value2, "cedula");
            return (Criteria) this;
        }

        public Criteria andCedulaNotBetween(Integer value1, Integer value2) {
            addCriterion("cedula not between", value1, value2, "cedula");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("nombre is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("nombre is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("nombre =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("nombre <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("nombre >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("nombre >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("nombre <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("nombre <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("nombre like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("nombre not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("nombre in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("nombre not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("nombre between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("nombre not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andApellido_1IsNull() {
            addCriterion("apellido_1 is null");
            return (Criteria) this;
        }

        public Criteria andApellido_1IsNotNull() {
            addCriterion("apellido_1 is not null");
            return (Criteria) this;
        }

        public Criteria andApellido_1EqualTo(String value) {
            addCriterion("apellido_1 =", value, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1NotEqualTo(String value) {
            addCriterion("apellido_1 <>", value, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1GreaterThan(String value) {
            addCriterion("apellido_1 >", value, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1GreaterThanOrEqualTo(String value) {
            addCriterion("apellido_1 >=", value, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1LessThan(String value) {
            addCriterion("apellido_1 <", value, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1LessThanOrEqualTo(String value) {
            addCriterion("apellido_1 <=", value, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1Like(String value) {
            addCriterion("apellido_1 like", value, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1NotLike(String value) {
            addCriterion("apellido_1 not like", value, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1In(List<String> values) {
            addCriterion("apellido_1 in", values, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1NotIn(List<String> values) {
            addCriterion("apellido_1 not in", values, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1Between(String value1, String value2) {
            addCriterion("apellido_1 between", value1, value2, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_1NotBetween(String value1, String value2) {
            addCriterion("apellido_1 not between", value1, value2, "apellido_1");
            return (Criteria) this;
        }

        public Criteria andApellido_2IsNull() {
            addCriterion("apellido_2 is null");
            return (Criteria) this;
        }

        public Criteria andApellido_2IsNotNull() {
            addCriterion("apellido_2 is not null");
            return (Criteria) this;
        }

        public Criteria andApellido_2EqualTo(String value) {
            addCriterion("apellido_2 =", value, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2NotEqualTo(String value) {
            addCriterion("apellido_2 <>", value, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2GreaterThan(String value) {
            addCriterion("apellido_2 >", value, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2GreaterThanOrEqualTo(String value) {
            addCriterion("apellido_2 >=", value, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2LessThan(String value) {
            addCriterion("apellido_2 <", value, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2LessThanOrEqualTo(String value) {
            addCriterion("apellido_2 <=", value, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2Like(String value) {
            addCriterion("apellido_2 like", value, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2NotLike(String value) {
            addCriterion("apellido_2 not like", value, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2In(List<String> values) {
            addCriterion("apellido_2 in", values, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2NotIn(List<String> values) {
            addCriterion("apellido_2 not in", values, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2Between(String value1, String value2) {
            addCriterion("apellido_2 between", value1, value2, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andApellido_2NotBetween(String value1, String value2) {
            addCriterion("apellido_2 not between", value1, value2, "apellido_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_1IsNull() {
            addCriterion("telefono_1 is null");
            return (Criteria) this;
        }

        public Criteria andTelefono_1IsNotNull() {
            addCriterion("telefono_1 is not null");
            return (Criteria) this;
        }

        public Criteria andTelefono_1EqualTo(Integer value) {
            addCriterion("telefono_1 =", value, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1NotEqualTo(Integer value) {
            addCriterion("telefono_1 <>", value, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1GreaterThan(Integer value) {
            addCriterion("telefono_1 >", value, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1GreaterThanOrEqualTo(Integer value) {
            addCriterion("telefono_1 >=", value, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1LessThan(Integer value) {
            addCriterion("telefono_1 <", value, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1LessThanOrEqualTo(Integer value) {
            addCriterion("telefono_1 <=", value, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1In(List<Integer> values) {
            addCriterion("telefono_1 in", values, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1NotIn(List<Integer> values) {
            addCriterion("telefono_1 not in", values, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1Between(Integer value1, Integer value2) {
            addCriterion("telefono_1 between", value1, value2, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_1NotBetween(Integer value1, Integer value2) {
            addCriterion("telefono_1 not between", value1, value2, "telefono_1");
            return (Criteria) this;
        }

        public Criteria andTelefono_2IsNull() {
            addCriterion("telefono_2 is null");
            return (Criteria) this;
        }

        public Criteria andTelefono_2IsNotNull() {
            addCriterion("telefono_2 is not null");
            return (Criteria) this;
        }

        public Criteria andTelefono_2EqualTo(Integer value) {
            addCriterion("telefono_2 =", value, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2NotEqualTo(Integer value) {
            addCriterion("telefono_2 <>", value, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2GreaterThan(Integer value) {
            addCriterion("telefono_2 >", value, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2GreaterThanOrEqualTo(Integer value) {
            addCriterion("telefono_2 >=", value, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2LessThan(Integer value) {
            addCriterion("telefono_2 <", value, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2LessThanOrEqualTo(Integer value) {
            addCriterion("telefono_2 <=", value, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2In(List<Integer> values) {
            addCriterion("telefono_2 in", values, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2NotIn(List<Integer> values) {
            addCriterion("telefono_2 not in", values, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2Between(Integer value1, Integer value2) {
            addCriterion("telefono_2 between", value1, value2, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andTelefono_2NotBetween(Integer value1, Integer value2) {
            addCriterion("telefono_2 not between", value1, value2, "telefono_2");
            return (Criteria) this;
        }

        public Criteria andCorreoIsNull() {
            addCriterion("correo is null");
            return (Criteria) this;
        }

        public Criteria andCorreoIsNotNull() {
            addCriterion("correo is not null");
            return (Criteria) this;
        }

        public Criteria andCorreoEqualTo(String value) {
            addCriterion("correo =", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoNotEqualTo(String value) {
            addCriterion("correo <>", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoGreaterThan(String value) {
            addCriterion("correo >", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoGreaterThanOrEqualTo(String value) {
            addCriterion("correo >=", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoLessThan(String value) {
            addCriterion("correo <", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoLessThanOrEqualTo(String value) {
            addCriterion("correo <=", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoLike(String value) {
            addCriterion("correo like", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoNotLike(String value) {
            addCriterion("correo not like", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoIn(List<String> values) {
            addCriterion("correo in", values, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoNotIn(List<String> values) {
            addCriterion("correo not in", values, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoBetween(String value1, String value2) {
            addCriterion("correo between", value1, value2, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoNotBetween(String value1, String value2) {
            addCriterion("correo not between", value1, value2, "correo");
            return (Criteria) this;
        }

        public Criteria andDireccionIsNull() {
            addCriterion("direccion is null");
            return (Criteria) this;
        }

        public Criteria andDireccionIsNotNull() {
            addCriterion("direccion is not null");
            return (Criteria) this;
        }

        public Criteria andDireccionEqualTo(String value) {
            addCriterion("direccion =", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotEqualTo(String value) {
            addCriterion("direccion <>", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionGreaterThan(String value) {
            addCriterion("direccion >", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionGreaterThanOrEqualTo(String value) {
            addCriterion("direccion >=", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLessThan(String value) {
            addCriterion("direccion <", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLessThanOrEqualTo(String value) {
            addCriterion("direccion <=", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLike(String value) {
            addCriterion("direccion like", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotLike(String value) {
            addCriterion("direccion not like", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionIn(List<String> values) {
            addCriterion("direccion in", values, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotIn(List<String> values) {
            addCriterion("direccion not in", values, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionBetween(String value1, String value2) {
            addCriterion("direccion between", value1, value2, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotBetween(String value1, String value2) {
            addCriterion("direccion not between", value1, value2, "direccion");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoIsNull() {
            addCriterion("codigo_prog_academico is null");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoIsNotNull() {
            addCriterion("codigo_prog_academico is not null");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoEqualTo(String value) {
            addCriterion("codigo_prog_academico =", value, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoNotEqualTo(String value) {
            addCriterion("codigo_prog_academico <>", value, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoGreaterThan(String value) {
            addCriterion("codigo_prog_academico >", value, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_prog_academico >=", value, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoLessThan(String value) {
            addCriterion("codigo_prog_academico <", value, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoLessThanOrEqualTo(String value) {
            addCriterion("codigo_prog_academico <=", value, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoLike(String value) {
            addCriterion("codigo_prog_academico like", value, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoNotLike(String value) {
            addCriterion("codigo_prog_academico not like", value, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoIn(List<String> values) {
            addCriterion("codigo_prog_academico in", values, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoNotIn(List<String> values) {
            addCriterion("codigo_prog_academico not in", values, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoBetween(String value1, String value2) {
            addCriterion("codigo_prog_academico between", value1, value2, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_prog_academicoNotBetween(String value1, String value2) {
            addCriterion("codigo_prog_academico not between", value1, value2, "codigo_prog_academico");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoIsNull() {
            addCriterion("codigo_cargo is null");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoIsNotNull() {
            addCriterion("codigo_cargo is not null");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoEqualTo(String value) {
            addCriterion("codigo_cargo =", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoNotEqualTo(String value) {
            addCriterion("codigo_cargo <>", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoGreaterThan(String value) {
            addCriterion("codigo_cargo >", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_cargo >=", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoLessThan(String value) {
            addCriterion("codigo_cargo <", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoLessThanOrEqualTo(String value) {
            addCriterion("codigo_cargo <=", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoLike(String value) {
            addCriterion("codigo_cargo like", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoNotLike(String value) {
            addCriterion("codigo_cargo not like", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoIn(List<String> values) {
            addCriterion("codigo_cargo in", values, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoNotIn(List<String> values) {
            addCriterion("codigo_cargo not in", values, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoBetween(String value1, String value2) {
            addCriterion("codigo_cargo between", value1, value2, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoNotBetween(String value1, String value2) {
            addCriterion("codigo_cargo not between", value1, value2, "codigo_cargo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table persona
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 02 22:20:35 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}