package com.practica.dao.general.model;

public class Usuario {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id_usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private Integer id_usuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id_persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private Integer id_persona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.nombre_usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String nombre_usuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.contrasena
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    private String contrasena;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id_usuario
     *
     * @return the value of usuario.id_usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public Integer getId_usuario() {
        return id_usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id_usuario
     *
     * @param id_usuario the value for usuario.id_usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setId_usuario(Integer id_usuario) {
        this.id_usuario = id_usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id_persona
     *
     * @return the value of usuario.id_persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public Integer getId_persona() {
        return id_persona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id_persona
     *
     * @param id_persona the value for usuario.id_persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setId_persona(Integer id_persona) {
        this.id_persona = id_persona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.nombre_usuario
     *
     * @return the value of usuario.nombre_usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getNombre_usuario() {
        return nombre_usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.nombre_usuario
     *
     * @param nombre_usuario the value for usuario.nombre_usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setNombre_usuario(String nombre_usuario) {
        this.nombre_usuario = nombre_usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.contrasena
     *
     * @return the value of usuario.contrasena
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public String getContrasena() {
        return contrasena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.contrasena
     *
     * @param contrasena the value for usuario.contrasena
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
}