package com.practica.dao.general.map;

import com.practica.dao.general.model.Persona;
import com.practica.dao.general.model.PersonaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    long countByExample(PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int deleteByExample(PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int deleteByPrimaryKey(Integer cedula);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int insert(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int insertSelective(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    List<Persona> selectByExample(PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    Persona selectByPrimaryKey(Integer cedula);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int updateByExampleSelective(@Param("record") Persona record, @Param("example") PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int updateByExample(@Param("record") Persona record, @Param("example") PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int updateByPrimaryKeySelective(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persona
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int updateByPrimaryKey(Persona record);
}