package com.practica.dao.general.map;

import com.practica.dao.general.model.Usuario;
import com.practica.dao.general.model.UsuarioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    long countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int deleteByPrimaryKey(Integer id_usuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    Usuario selectByPrimaryKey(Integer id_usuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Mon Apr 02 22:20:35 COT 2018
     */
    int updateByPrimaryKey(Usuario record);
}