package com.practica.dao.coordinacion.model;

import java.util.ArrayList;
import java.util.List;

public class CargoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public CargoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodigo_cargoIsNull() {
            addCriterion("codigo_cargo is null");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoIsNotNull() {
            addCriterion("codigo_cargo is not null");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoEqualTo(String value) {
            addCriterion("codigo_cargo =", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoNotEqualTo(String value) {
            addCriterion("codigo_cargo <>", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoGreaterThan(String value) {
            addCriterion("codigo_cargo >", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_cargo >=", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoLessThan(String value) {
            addCriterion("codigo_cargo <", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoLessThanOrEqualTo(String value) {
            addCriterion("codigo_cargo <=", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoLike(String value) {
            addCriterion("codigo_cargo like", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoNotLike(String value) {
            addCriterion("codigo_cargo not like", value, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoIn(List<String> values) {
            addCriterion("codigo_cargo in", values, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoNotIn(List<String> values) {
            addCriterion("codigo_cargo not in", values, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoBetween(String value1, String value2) {
            addCriterion("codigo_cargo between", value1, value2, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andCodigo_cargoNotBetween(String value1, String value2) {
            addCriterion("codigo_cargo not between", value1, value2, "codigo_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoIsNull() {
            addCriterion("nombre_cargo is null");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoIsNotNull() {
            addCriterion("nombre_cargo is not null");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoEqualTo(String value) {
            addCriterion("nombre_cargo =", value, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoNotEqualTo(String value) {
            addCriterion("nombre_cargo <>", value, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoGreaterThan(String value) {
            addCriterion("nombre_cargo >", value, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoGreaterThanOrEqualTo(String value) {
            addCriterion("nombre_cargo >=", value, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoLessThan(String value) {
            addCriterion("nombre_cargo <", value, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoLessThanOrEqualTo(String value) {
            addCriterion("nombre_cargo <=", value, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoLike(String value) {
            addCriterion("nombre_cargo like", value, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoNotLike(String value) {
            addCriterion("nombre_cargo not like", value, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoIn(List<String> values) {
            addCriterion("nombre_cargo in", values, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoNotIn(List<String> values) {
            addCriterion("nombre_cargo not in", values, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoBetween(String value1, String value2) {
            addCriterion("nombre_cargo between", value1, value2, "nombre_cargo");
            return (Criteria) this;
        }

        public Criteria andNombre_cargoNotBetween(String value1, String value2) {
            addCriterion("nombre_cargo not between", value1, value2, "nombre_cargo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cargo
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 02 22:22:08 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cargo
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}