package com.practica.dao.coordinacion.model;

public class Empresa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empresa.nit_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String nit_empresa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empresa.nombre_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String nombre_empresa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empresa.direccion_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String direccion_empresa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empresa.telefono_1_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer telefono_1_empresa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empresa.telefono_2_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer telefono_2_empresa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empresa.ciudad_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String ciudad_empresa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empresa.nit_empresa
     *
     * @return the value of empresa.nit_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getNit_empresa() {
        return nit_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empresa.nit_empresa
     *
     * @param nit_empresa the value for empresa.nit_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setNit_empresa(String nit_empresa) {
        this.nit_empresa = nit_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empresa.nombre_empresa
     *
     * @return the value of empresa.nombre_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getNombre_empresa() {
        return nombre_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empresa.nombre_empresa
     *
     * @param nombre_empresa the value for empresa.nombre_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setNombre_empresa(String nombre_empresa) {
        this.nombre_empresa = nombre_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empresa.direccion_empresa
     *
     * @return the value of empresa.direccion_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getDireccion_empresa() {
        return direccion_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empresa.direccion_empresa
     *
     * @param direccion_empresa the value for empresa.direccion_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setDireccion_empresa(String direccion_empresa) {
        this.direccion_empresa = direccion_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empresa.telefono_1_empresa
     *
     * @return the value of empresa.telefono_1_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getTelefono_1_empresa() {
        return telefono_1_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empresa.telefono_1_empresa
     *
     * @param telefono_1_empresa the value for empresa.telefono_1_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setTelefono_1_empresa(Integer telefono_1_empresa) {
        this.telefono_1_empresa = telefono_1_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empresa.telefono_2_empresa
     *
     * @return the value of empresa.telefono_2_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getTelefono_2_empresa() {
        return telefono_2_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empresa.telefono_2_empresa
     *
     * @param telefono_2_empresa the value for empresa.telefono_2_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setTelefono_2_empresa(Integer telefono_2_empresa) {
        this.telefono_2_empresa = telefono_2_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empresa.ciudad_empresa
     *
     * @return the value of empresa.ciudad_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getCiudad_empresa() {
        return ciudad_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empresa.ciudad_empresa
     *
     * @param ciudad_empresa the value for empresa.ciudad_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setCiudad_empresa(String ciudad_empresa) {
        this.ciudad_empresa = ciudad_empresa;
    }
}