package com.practica.dao.coordinacion.model;

import java.util.ArrayList;
import java.util.List;

public class EmpresaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public EmpresaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNit_empresaIsNull() {
            addCriterion("nit_empresa is null");
            return (Criteria) this;
        }

        public Criteria andNit_empresaIsNotNull() {
            addCriterion("nit_empresa is not null");
            return (Criteria) this;
        }

        public Criteria andNit_empresaEqualTo(String value) {
            addCriterion("nit_empresa =", value, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaNotEqualTo(String value) {
            addCriterion("nit_empresa <>", value, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaGreaterThan(String value) {
            addCriterion("nit_empresa >", value, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaGreaterThanOrEqualTo(String value) {
            addCriterion("nit_empresa >=", value, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaLessThan(String value) {
            addCriterion("nit_empresa <", value, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaLessThanOrEqualTo(String value) {
            addCriterion("nit_empresa <=", value, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaLike(String value) {
            addCriterion("nit_empresa like", value, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaNotLike(String value) {
            addCriterion("nit_empresa not like", value, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaIn(List<String> values) {
            addCriterion("nit_empresa in", values, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaNotIn(List<String> values) {
            addCriterion("nit_empresa not in", values, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaBetween(String value1, String value2) {
            addCriterion("nit_empresa between", value1, value2, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNit_empresaNotBetween(String value1, String value2) {
            addCriterion("nit_empresa not between", value1, value2, "nit_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaIsNull() {
            addCriterion("nombre_empresa is null");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaIsNotNull() {
            addCriterion("nombre_empresa is not null");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaEqualTo(String value) {
            addCriterion("nombre_empresa =", value, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaNotEqualTo(String value) {
            addCriterion("nombre_empresa <>", value, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaGreaterThan(String value) {
            addCriterion("nombre_empresa >", value, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaGreaterThanOrEqualTo(String value) {
            addCriterion("nombre_empresa >=", value, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaLessThan(String value) {
            addCriterion("nombre_empresa <", value, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaLessThanOrEqualTo(String value) {
            addCriterion("nombre_empresa <=", value, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaLike(String value) {
            addCriterion("nombre_empresa like", value, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaNotLike(String value) {
            addCriterion("nombre_empresa not like", value, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaIn(List<String> values) {
            addCriterion("nombre_empresa in", values, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaNotIn(List<String> values) {
            addCriterion("nombre_empresa not in", values, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaBetween(String value1, String value2) {
            addCriterion("nombre_empresa between", value1, value2, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andNombre_empresaNotBetween(String value1, String value2) {
            addCriterion("nombre_empresa not between", value1, value2, "nombre_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaIsNull() {
            addCriterion("direccion_empresa is null");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaIsNotNull() {
            addCriterion("direccion_empresa is not null");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaEqualTo(String value) {
            addCriterion("direccion_empresa =", value, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaNotEqualTo(String value) {
            addCriterion("direccion_empresa <>", value, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaGreaterThan(String value) {
            addCriterion("direccion_empresa >", value, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaGreaterThanOrEqualTo(String value) {
            addCriterion("direccion_empresa >=", value, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaLessThan(String value) {
            addCriterion("direccion_empresa <", value, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaLessThanOrEqualTo(String value) {
            addCriterion("direccion_empresa <=", value, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaLike(String value) {
            addCriterion("direccion_empresa like", value, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaNotLike(String value) {
            addCriterion("direccion_empresa not like", value, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaIn(List<String> values) {
            addCriterion("direccion_empresa in", values, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaNotIn(List<String> values) {
            addCriterion("direccion_empresa not in", values, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaBetween(String value1, String value2) {
            addCriterion("direccion_empresa between", value1, value2, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andDireccion_empresaNotBetween(String value1, String value2) {
            addCriterion("direccion_empresa not between", value1, value2, "direccion_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaIsNull() {
            addCriterion("telefono_1_empresa is null");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaIsNotNull() {
            addCriterion("telefono_1_empresa is not null");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaEqualTo(Integer value) {
            addCriterion("telefono_1_empresa =", value, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaNotEqualTo(Integer value) {
            addCriterion("telefono_1_empresa <>", value, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaGreaterThan(Integer value) {
            addCriterion("telefono_1_empresa >", value, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaGreaterThanOrEqualTo(Integer value) {
            addCriterion("telefono_1_empresa >=", value, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaLessThan(Integer value) {
            addCriterion("telefono_1_empresa <", value, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaLessThanOrEqualTo(Integer value) {
            addCriterion("telefono_1_empresa <=", value, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaIn(List<Integer> values) {
            addCriterion("telefono_1_empresa in", values, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaNotIn(List<Integer> values) {
            addCriterion("telefono_1_empresa not in", values, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaBetween(Integer value1, Integer value2) {
            addCriterion("telefono_1_empresa between", value1, value2, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_1_empresaNotBetween(Integer value1, Integer value2) {
            addCriterion("telefono_1_empresa not between", value1, value2, "telefono_1_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaIsNull() {
            addCriterion("telefono_2_empresa is null");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaIsNotNull() {
            addCriterion("telefono_2_empresa is not null");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaEqualTo(Integer value) {
            addCriterion("telefono_2_empresa =", value, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaNotEqualTo(Integer value) {
            addCriterion("telefono_2_empresa <>", value, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaGreaterThan(Integer value) {
            addCriterion("telefono_2_empresa >", value, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaGreaterThanOrEqualTo(Integer value) {
            addCriterion("telefono_2_empresa >=", value, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaLessThan(Integer value) {
            addCriterion("telefono_2_empresa <", value, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaLessThanOrEqualTo(Integer value) {
            addCriterion("telefono_2_empresa <=", value, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaIn(List<Integer> values) {
            addCriterion("telefono_2_empresa in", values, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaNotIn(List<Integer> values) {
            addCriterion("telefono_2_empresa not in", values, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaBetween(Integer value1, Integer value2) {
            addCriterion("telefono_2_empresa between", value1, value2, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andTelefono_2_empresaNotBetween(Integer value1, Integer value2) {
            addCriterion("telefono_2_empresa not between", value1, value2, "telefono_2_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaIsNull() {
            addCriterion("ciudad_empresa is null");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaIsNotNull() {
            addCriterion("ciudad_empresa is not null");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaEqualTo(String value) {
            addCriterion("ciudad_empresa =", value, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaNotEqualTo(String value) {
            addCriterion("ciudad_empresa <>", value, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaGreaterThan(String value) {
            addCriterion("ciudad_empresa >", value, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaGreaterThanOrEqualTo(String value) {
            addCriterion("ciudad_empresa >=", value, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaLessThan(String value) {
            addCriterion("ciudad_empresa <", value, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaLessThanOrEqualTo(String value) {
            addCriterion("ciudad_empresa <=", value, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaLike(String value) {
            addCriterion("ciudad_empresa like", value, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaNotLike(String value) {
            addCriterion("ciudad_empresa not like", value, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaIn(List<String> values) {
            addCriterion("ciudad_empresa in", values, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaNotIn(List<String> values) {
            addCriterion("ciudad_empresa not in", values, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaBetween(String value1, String value2) {
            addCriterion("ciudad_empresa between", value1, value2, "ciudad_empresa");
            return (Criteria) this;
        }

        public Criteria andCiudad_empresaNotBetween(String value1, String value2) {
            addCriterion("ciudad_empresa not between", value1, value2, "ciudad_empresa");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empresa
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 02 22:22:08 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}