package com.practica.dao.coordinacion.model;

public class HojaVida {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoja_vida.id_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer id_hoja_vida;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoja_vida.id_persona
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer id_persona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoja_vida.id_prog_academico
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String id_prog_academico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoja_vida.fecha_guardado
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer fecha_guardado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoja_vida.archivo_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String archivo_hoja_vida;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoja_vida.id_hoja_vida
     *
     * @return the value of hoja_vida.id_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getId_hoja_vida() {
        return id_hoja_vida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoja_vida.id_hoja_vida
     *
     * @param id_hoja_vida the value for hoja_vida.id_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setId_hoja_vida(Integer id_hoja_vida) {
        this.id_hoja_vida = id_hoja_vida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoja_vida.id_persona
     *
     * @return the value of hoja_vida.id_persona
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getId_persona() {
        return id_persona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoja_vida.id_persona
     *
     * @param id_persona the value for hoja_vida.id_persona
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setId_persona(Integer id_persona) {
        this.id_persona = id_persona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoja_vida.id_prog_academico
     *
     * @return the value of hoja_vida.id_prog_academico
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getId_prog_academico() {
        return id_prog_academico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoja_vida.id_prog_academico
     *
     * @param id_prog_academico the value for hoja_vida.id_prog_academico
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setId_prog_academico(String id_prog_academico) {
        this.id_prog_academico = id_prog_academico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoja_vida.fecha_guardado
     *
     * @return the value of hoja_vida.fecha_guardado
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getFecha_guardado() {
        return fecha_guardado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoja_vida.fecha_guardado
     *
     * @param fecha_guardado the value for hoja_vida.fecha_guardado
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setFecha_guardado(Integer fecha_guardado) {
        this.fecha_guardado = fecha_guardado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoja_vida.archivo_hoja_vida
     *
     * @return the value of hoja_vida.archivo_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getArchivo_hoja_vida() {
        return archivo_hoja_vida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoja_vida.archivo_hoja_vida
     *
     * @param archivo_hoja_vida the value for hoja_vida.archivo_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setArchivo_hoja_vida(String archivo_hoja_vida) {
        this.archivo_hoja_vida = archivo_hoja_vida;
    }
}