package com.practica.dao.coordinacion.model;

public class PracticaEstudiante {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practica_estudiante.id_practica
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer id_practica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practica_estudiante.id_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer id_hoja_vida;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practica_estudiante.id_persona
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer id_persona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practica_estudiante.id_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String id_empresa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practica_estudiante.id_docente
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private Integer id_docente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practica_estudiante.id_practica
     *
     * @return the value of practica_estudiante.id_practica
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getId_practica() {
        return id_practica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practica_estudiante.id_practica
     *
     * @param id_practica the value for practica_estudiante.id_practica
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setId_practica(Integer id_practica) {
        this.id_practica = id_practica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practica_estudiante.id_hoja_vida
     *
     * @return the value of practica_estudiante.id_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getId_hoja_vida() {
        return id_hoja_vida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practica_estudiante.id_hoja_vida
     *
     * @param id_hoja_vida the value for practica_estudiante.id_hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setId_hoja_vida(Integer id_hoja_vida) {
        this.id_hoja_vida = id_hoja_vida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practica_estudiante.id_persona
     *
     * @return the value of practica_estudiante.id_persona
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getId_persona() {
        return id_persona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practica_estudiante.id_persona
     *
     * @param id_persona the value for practica_estudiante.id_persona
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setId_persona(Integer id_persona) {
        this.id_persona = id_persona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practica_estudiante.id_empresa
     *
     * @return the value of practica_estudiante.id_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practica_estudiante.id_empresa
     *
     * @param id_empresa the value for practica_estudiante.id_empresa
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practica_estudiante.id_docente
     *
     * @return the value of practica_estudiante.id_docente
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public Integer getId_docente() {
        return id_docente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practica_estudiante.id_docente
     *
     * @param id_docente the value for practica_estudiante.id_docente
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setId_docente(Integer id_docente) {
        this.id_docente = id_docente;
    }
}