package com.practica.dao.coordinacion.model;

public class ProgramaAcademico {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programa_academico.codigo_academico
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String codigo_academico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programa_academico.nombre
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programa_academico.codigo_academico
     *
     * @return the value of programa_academico.codigo_academico
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getCodigo_academico() {
        return codigo_academico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programa_academico.codigo_academico
     *
     * @param codigo_academico the value for programa_academico.codigo_academico
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setCodigo_academico(String codigo_academico) {
        this.codigo_academico = codigo_academico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programa_academico.nombre
     *
     * @return the value of programa_academico.nombre
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programa_academico.nombre
     *
     * @param nombre the value for programa_academico.nombre
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}