package com.practica.dao.coordinacion.map;

import com.practica.dao.coordinacion.model.HojaVida;
import com.practica.dao.coordinacion.model.HojaVidaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HojaVidaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    long countByExample(HojaVidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int deleteByExample(HojaVidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int deleteByPrimaryKey(Integer id_hoja_vida);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int insert(HojaVida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int insertSelective(HojaVida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    List<HojaVida> selectByExample(HojaVidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    HojaVida selectByPrimaryKey(Integer id_hoja_vida);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int updateByExampleSelective(@Param("record") HojaVida record, @Param("example") HojaVidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int updateByExample(@Param("record") HojaVida record, @Param("example") HojaVidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int updateByPrimaryKeySelective(HojaVida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hoja_vida
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int updateByPrimaryKey(HojaVida record);
}