package com.practica.dao.coordinacion.map;

import com.practica.dao.coordinacion.model.PracticaEstudiante;
import com.practica.dao.coordinacion.model.PracticaEstudianteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PracticaEstudianteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    long countByExample(PracticaEstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int deleteByExample(PracticaEstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int deleteByPrimaryKey(Integer id_practica);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int insert(PracticaEstudiante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int insertSelective(PracticaEstudiante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    List<PracticaEstudiante> selectByExample(PracticaEstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    PracticaEstudiante selectByPrimaryKey(Integer id_practica);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int updateByExampleSelective(@Param("record") PracticaEstudiante record, @Param("example") PracticaEstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int updateByExample(@Param("record") PracticaEstudiante record, @Param("example") PracticaEstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int updateByPrimaryKeySelective(PracticaEstudiante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practica_estudiante
     *
     * @mbg.generated Mon Apr 02 22:22:08 COT 2018
     */
    int updateByPrimaryKey(PracticaEstudiante record);
}